import { Anchor, Container, Stack, Text, Title } from "@mantine/core";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Terms and Conditions - Brain Dead Eating",
};

const CONTACT_EMAIL = "privacy@braindeadeating.com";

export default function TermsPage() {
	return (
		<Container size={480} py="xl">
			<Anchor href="/" size="sm" c="dimmed" mb="md" display="block">
				Back to home
			</Anchor>

			<Title order={2} mb="xl" style={{ letterSpacing: "-0.02em" }}>
				Terms and Conditions
			</Title>

			<Stack gap="lg">
				<Text c="dimmed" size="sm">
					Last updated: April 9, 2026
				</Text>

				<section>
					<Title order={4} mb="xs">
						Agreement to Terms
					</Title>
					<Text size="md">
						By accessing or using Brain Dead Eating, you agree to be bound by
						these terms. If you do not agree, do not use the service.
					</Text>
				</section>

				<section>
					<Title order={4} mb="xs">
						What the Service Does
					</Title>
					<Text size="md">
						Brain Dead Eating is a calorie tracking app. You describe what you
						ate in plain language, and we use AI to estimate the nutritional
						content. That is it.
					</Text>
				</section>

				<section>
					<Title order={4} mb="xs">
						Not Medical Advice
					</Title>
					<Text size="md">
						This app is not a medical device. Calorie and macro estimates are
						approximate and generated by AI. Do not use this app as a
						substitute for professional medical or nutritional advice. If you
						have a medical condition or eating disorder, consult a healthcare
						professional before using this service.
					</Text>
				</section>

				<section>
					<Title order={4} mb="xs">
						Accuracy of Estimates
					</Title>
					<Text size="md">
						Nutritional estimates are powered by AI and are not guaranteed to be
						accurate. Actual calorie and macro values may vary based on portion
						sizes, preparation methods, brands, and ingredients. We round
						calories to the nearest 5 and macros to the nearest gram.
					</Text>
				</section>

				<section>
					<Title order={4} mb="xs">
						Your Account
					</Title>
					<Text size="md">
						You sign in with your Google account. You are responsible for
						maintaining the security of that account. You may delete your
						account and all associated data at any time from your profile page.
					</Text>
				</section>

				<section>
					<Title order={4} mb="xs">
						Acceptable Use
					</Title>
					<Text size="md">
						Do not misuse the service. This includes attempting to circumvent
						usage limits, access other users' data, or interfere with the
						operation of the app. We reserve the right to suspend or terminate
						accounts that violate these terms.
					</Text>
				</section>

				<section>
					<Title order={4} mb="xs">
						Usage Limits
					</Title>
					<Text size="md">
						Free accounts are limited to 5 AI-powered food logs per day. Pro
						accounts are limited to 25. These limits may change at any time.
					</Text>
				</section>

				<section>
					<Title order={4} mb="xs">
						Subscriptions and Payments
					</Title>
					<Text size="md">
						Pro subscriptions may be offered through Apple or Google in-app
						purchases. Subscription terms, pricing, billing, and refund
						policies are governed by the respective app store. We may also
						offer promotional access through promo codes with a set duration.
					</Text>
				</section>

				<section>
					<Title order={4} mb="xs">
						Intellectual Property
					</Title>
					<Text size="md">
						The Brain Dead Eating name, logo, and app design are our property.
						Your food logs and personal data belong to you. You can export your
						data at any time.
					</Text>
				</section>

				<section>
					<Title order={4} mb="xs">
						Third-Party Services
					</Title>
					<Text size="md">
						We use OpenAI to process food descriptions, Google for
						authentication, MongoDB Atlas for data storage, and Vercel for
						hosting. Your use of the app is also subject to these providers'
						terms of service.
					</Text>
				</section>

				<section>
					<Title order={4} mb="xs">
						Limitation of Liability
					</Title>
					<Text size="md">
						Brain Dead Eating is provided as-is, without warranty of any kind.
						We are not liable for any damages resulting from your use of the
						service, including but not limited to health decisions made based on
						calorie estimates. Use common sense.
					</Text>
				</section>

				<section>
					<Title order={4} mb="xs">
						Termination
					</Title>
					<Text size="md">
						We may suspend or terminate your access at any time for violation of
						these terms. You may stop using the service and delete your account
						at any time.
					</Text>
				</section>

				<section>
					<Title order={4} mb="xs">
						Changes to These Terms
					</Title>
					<Text size="md">
						We may update these terms at any time. If we make significant
						changes, we will notify you in the app. Continued use of the
						service after changes constitutes acceptance.
					</Text>
				</section>

				<section>
					<Title order={4} mb="xs">
						Contact
					</Title>
					<Text size="md">
						Questions about these terms? Email {CONTACT_EMAIL}.
					</Text>
				</section>
			</Stack>
		</Container>
	);
}
